### ISSUE TITLE
Extensión Manual controller

### ISSUE THREAD

**Issue by rafa-casado** [I3A-NavSys/navsim#22]
Víctor, te dejo algunos comentarios:

- la línea del plot **Z angular velocity (rad/s)** debe ser de color naranja, como el color del campo correspondiente en la extensión **COMMAND GENERATOR**.
- haz la línea de todos los plots un píxel más gruesa (si se puede).
- los botones **START STOP** los pasas al dropdown de **Controls power**. Eso permite minimizar el desplegable de visualización. Puedes renombrarlo a **Control** o algo así.
- ¿Es posible poner en un solo botón conmutable las funciones **START** y **STOP**?

**Comment by BlazquezVictor** [comment]
Perfecto, me pongo manos a la obra. Lo de la línea más grueso de los plots tengo que investigarlo, pero lo del botón conmutable de START y STOP desde luego que sí se puede hacer.
A lo largo de esta mañana deberé tenerlo hecho.

**Comment by rafa-casado** [comment]
Te está quedando genial. Mas mejoras que se me ocurren:

- renombra la cámara para que se llame **manual controller CAM** o algo similar.
- Renombra **Linear velocity** a **Linear Velocity Max**. Aumenta el rango hasta 10m/s.
- Renombra **Angular velocity** a **Angular Velocity Max**. Aumenta el rango hasta 6rad/s.
- Al cambiar el valor de las velocidades, se reajuste automáticamente, sin necesidad de reiniciar el joystick.
- Junto al botón de START/STOP pon un checkbox **ON** para iniciar con los motores apagados, o encendidos. Así evitamos que al estar flotando en el aire, al enganchar el joystick se caiga hasta que lo recuperes.
- En el futuro podemos poner unos puntitos de configuración donde se pueda elegir invertir los ejes.

**Comment by BlazquezVictor** [comment]
Todos esos cambios ya están implementados. Dejo la issue abierta por si encuentras algún bug o se te ocurre alguna otra mejora.

**Comment by rafa-casado** [comment]
Genial. Un par de cosas que he observado:
- Pon la nueva cámara invisible. Ahora se ve en la vista panorámica.
- No debería poder acercarme a una distancia menor de cero. En realidad déjale un margen de 1 metro o medio metro.

**Comment by BlazquezVictor** [comment]
- Yo no veía la cámara, pero igualmente ahora le he puesto que sea invisible.
- Ahora ya no te puedes acercar a más de 1 metro de distancia. No he puesto límite de distancia máxima porque en función del tamaño del UAV que se maneje habrá que alejarse más o menos. Pero podemos poner uno ahora para el aerotaxi.

**Comment by BlazquezVictor** [comment]
Issue cerrada hasta que se piensen nuevas adiciones a la extensión.
