### ISSUE TITLE
Comprobar gráfica de velocidad del Flight Plan

### ISSUE THREAD

**Issue by inamoriza** [I3A-NavSys/navsim#4]
En el Flight Plan, la gráfica de velocidad muestra el plan en coordenadas globales. Comprobar que los datos de telemetría recibidos del dron también lo hace (se sospecha que puedan estar en coordenadas locales).

**Comment by BlazquezVictor** [comment]
El problema era que no se pasaba la velocidad en el sistema global, ahora sí, tanto a la función de GetCommand del FlightPlan como al la telemetría del UAV
