### ISSUE TITLE
Mejorar la robustez del Flight Plan

### ISSUE THREAD

**Issue by inamoriza** [I3A-NavSys/navsim#8]
1. Corregir la discontinuidad entre waypoints que puede producirse al introducirlos manualmente.

**Comment by BlazquezVictor** [comment]
Como añadido se puede implementar, en un futuro, una funcionalidad que permita guardar y cargar flightplans en formato .json, por ejemplo

**Comment by BlazquezVictor** [comment]
1. Cambiar los nombres de los métodos de suavizado de curvas del FP.
2. Implementar el método setUniformVelocity y eliminar setTimeFromVel y setV000

**Comment by BlazquezVictor** [comment]
Valorar si añadimos al FlightPlan que tenga en cuenta una orientación dada y, por tanto, bloquee la rotación que se calcula en cada iteración.

**Comment by BlazquezVictor** [comment]
Manejo de la inserción manual de waypoints arreglada (función SetWaypoint).
Los métodos de suavizado han sido renombrados.
Se ha implementado el método SetUniformVelocity y eliminado el SetTimeFromVel y SetV000.

**Comment by BlazquezVictor** [comment]
Me da la sensación de que falta por arreglar que el dron no avance hacia abajo cuando debe ir simplemente hacia delante. Hay que mirarlo bien.

**Comment by BlazquezVictor** [comment]
Con el FlightPlan debe estar resuelto
