### ISSUE TITLE
Actualizaciones de rama MAIN

### ISSUE THREAD

**Issue by rafa-casado** [I3A-NavSys/navsim#9]
Pasos:

1. Duplicar rama **dev** a una rama temporal **gazebo**.
2. Eliminar de la rama **gazebo** todo rastro del desarrollo para NVIDIA Omniverse.
3. Actualizar la rama **main** con la rama **gazebo**.
4. Generar una nueva release de la herramienta.
5. Eliminar la rama **gazebo**.

**Comment by inamoriza** [comment]
Release de Navsim Gazebo v1.0.0
